# Generated by Django 3.2.25 on 2024-11-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
